dev:
  postgres:
    url: "jdbc:postgresql://localhost:5432/postgres"
    user: "postgres"
    password: "Dharmavaram1@"
    driver: "org.postgresql.Driver"
    port: 5432

  oracle:
    username: "test123"
    password: "oracle_password"
    connection_string: "jdbc:oracle:thin:@//dev-db-host:1521/ORCL"

  adls:
    account_name: "myadlsdevaccount"
    account_key: "myadlsdevkey"

qa:
  postgres:
    url: "jdbc:postgresql://localhost:5432/postgres"
    user: "postgres"
    password: "Dharmavaram1@"
    driver: "org.postgresql.Driver"
    port: 5432

  sqlserver_c:
    url: "jdbc:sqlserver://decautoserver.database.windows.net:1433;database=decauto"
    user: "decadmin"
    password: "Dharmavaram1@"
    driver: "com.microsoft.sqlserver.jdbc.SQLServerDriver"

  sqlserver_l:
    url: "jdbc:sqlserver://decautoserver.database.windows.net:1433;database=decauto"
    user: "decadmin"
    password: "Dharmavaram1@"
    driver: "com.microsoft.sqlserver.jdbc.SQLServerDriver"

  adls:
    adls_account_name: "decautoadls"
    adls_container_name: "test"
    key: "Key"  # Your Account Key

prod:
  postgres:
    url: "jdbc:postgresql://localhost:5432/postgres"
    user: "postgres"
    password: "Dharmavaram1@"
    driver: "org.postgresql.Driver"
    port: 5432
  oracle:
    username: "oracle_user"
    password: "oracle_password"
    connection_string: "jdbc:oracle:thin:@//dev-db-host:1521/ORCL"